package com.axa_space.axa_fmf_closenotification;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubmissionCompletedNautilus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Comments")
	private java.lang.String comments;
	@org.kie.api.definition.type.Label(value = "Approved")
	private java.lang.Boolean approved;
	@org.kie.api.definition.type.Label(value = "Rejected")
	private java.lang.Boolean rejected;

	public SubmissionCompletedNautilus() {
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public java.lang.Boolean getRejected() {
		return this.rejected;
	}

	public void setRejected(java.lang.Boolean rejected) {
		this.rejected = rejected;
	}

	public SubmissionCompletedNautilus(java.lang.String comments,
			java.lang.Boolean approved, java.lang.Boolean rejected) {
		this.comments = comments;
		this.approved = approved;
		this.rejected = rejected;
	}

}